# **European Drugs Development**

Team 10: Chamnan Suon

## **Executive Summary**

One of the two primary areas in our previous milestones discussed the influence of regulatory pathways on medicine authorization outcomes. This aligns with the domain question in Milestone2 on the association of regulatory pathways with medicine refusal outcome. Milestone4 will dive deeper into this area by expanding the regulatory pathway analysis and therapeutic_area analysis associated with the refusal outcome. Specifically, an additional feature revision_number is introduced to analyze further how regulatory pathways influence the refusal outcome. These extended analyses will help anchoring the domain question by answering subquestion such as how higher medicine revision number combined with regulatory pathways associated with refusal outcome? and is the refusal outcome structurally tied to the therapeutic domain than the pathways?
Previously, two assumptions were made and validated: the first assumption on regulatory features that were found to act together, proving the first assumption to be insufficient. Second assumption hovers around company behavior linked to refusal outcome, this assumption as well found to be invalidated as association rule mining analysis shows that refusal outcome strongly links to regulator pathway characteristics.
By performing a deeper analysis, I hope more interesting new insights will emerge which would help companies refine their strategies and improve the development process, ultimately increasing the likelihood of approved medicine. Additionally, this also helps with cost effectiveness as they would be able to focus on the areas that actually matter.

## **Data Dictionary**

 `drugs_dataset.csv`

|Column  |Class      |Description          |
|:-------|:----------|:--------------------|
|category|character | human or veterinary|
|medicine_name | character | brand name of the medicine|
|therapeutic_area | character | semicolon-separated list of therapeutic areas|
|common_name | character | international non-proprietary name (INN) or common name|
|active_substance | character | common name of the active chemical in the drug|
|product_number | character | EMEA/H/C/ (human) or EMEA/V/C/ (veterinary) number for the drug|
|patient_safety | logical | has patient safety notices|
|authorisation_status | character | whether the drug was authorised, withdrawn, or refused (or does not have a reported status)|
|atc_code | character | anatomical therapeutic chemical code|
|additional_monitoring | logical | when true, the medicine is under additional monitoring, meaning that it is monitored even more intensively than other medicines|
|generic | logical | whether the drug is a generic medicine, which is developed to be the same as a medicine that has already been authorised, called the reference medicine. A generic medicine contains the same active substance(s) as the reference medicine, and is used at the same dose(s) to treat the same disease(s)|
|biosimilar | logical | whether the drug is a biosimilar medicine, which is a biological medicine highly similar to another already approved biological medicine called the reference medicine.|
|conditional_approval | logical | whether the medicine received a conditional marketing authorisation. This was granted in the interest of public health because the medicine addresses an unmet medical need and the benefit of immediate availability outweighs the risk from less comprehensive data than normally required.|
|exceptional_circumstances | logical | whether the medicine was authorised under exceptional circumstances, because the applicant was unable to provide comprehensive data on the efficacy and safety of the medicine under normal conditions of use. This can happen because the condition to be treated is rare or because collection of full information is not possible or is unethical.|
|accelerated_assessment | logical | whether the medicine had an accelerated assessment. This means that it is a medicine of major interest for public health, so its timeframe for review was 150 evaluation days rather than 210.|
|orphan_medicine | logical | whether the medicine was designated an orphan medicine. This means that it was developed for use against a rare, life-threatening or chronically debilitating condition or, for economic reasons, it would be unlikely to have been developed without incentives.|
|marketing_authorisation_date | date | date on which the drug was authorised|
|date_of_refusal_of_marketing_authorisation | date | date on which the drug was refused|
|marketing_authorisation_holder_company_name | character | name of the company that is authorised to market the drug|
|pharmacotherapeutic_group | character | the target of the drug|
|date_of_opinion | date | date on which the opinion was made|
|decision_date | date | date on which the latest decision was made|
|revision_number | integer | integer revision number|
|condition_indication | character | language describing the specific uses of the drug|
|species | character | for veterinary medicines, the target species; might benefit from further cleaning|
|first_published | datetime | datetime when the information was first published|
|revision_date | datetime | datetime of the most recent revision|
|url | character | url for details about the drug and submission|

## **Data Cleaning and Preprocessing**

In [1]:
# Import pandas and numpy for DataFrame and operations
import pandas as pd
import numpy as np
import warnings

# Filter out DeprecationWarning for specific modules
warnings.filterwarnings("ignore", category=DeprecationWarning, module='jupyter_client')
warnings.filterwarnings("ignore", category=DeprecationWarning, module='matplotlib')
warnings.filterwarnings("ignore", category=DeprecationWarning, module='pyparsing')

print("Deprecation warnings are now suppressed.")

Deprecation warnings are now suppressed.

In [2]:
# Load dataset from github relative path
path = "https://raw.githubusercontent.com/SChamnan/ba820-unsupervised-ml-team10-project/refs/heads/main/european-drugs-development/drugs-dataset.csv"
drugs_df = pd.read_csv(path)
drugs_original=drugs_df.copy()
# Check out the first 5 rows of data
drugs_df.head(5)

,category,medicine_name,therapeutic_area,common_name,active_substance,product_number,patient_safety,authorisation_status,atc_code,additional_monitoring,...,marketing_authorisation_holder_company_name,pharmacotherapeutic_group,date_of_opinion,decision_date,revision_number,condition_indication,species,first_published,revision_date,url
0,human,Adcetris,"Lymphoma, Non-Hodgkin; Hodgkin Disease",brentuximab vedotin,brentuximab vedotin,2455,False,authorised,L01XC12,False,...,Takeda Pharma A/S,Antineoplastic agents,2012-07-19,2022-11-17,34.0,Hodgkin lymphomaAdcetris is indicated for adul...,NaN,2018-07-25T13:58:00Z,2023-03-13T11:52:00Z,https://www.ema.europa.eu/en/medicines/human/E...
1,human,Nityr,Tyrosinemias,nitisinone,nitisinone,4582,False,authorised,A16AX04,False,...,Cycle Pharmaceuticals (Europe) Ltd,"Other alimentary tract and metabolism products,",2018-05-31,2023-03-10,4.0,Treatment of adult and paediatric patients wit...,NaN,2018-07-26T14:20:00Z,2023-03-10T17:29:00Z,https://www.ema.europa.eu/en/medicines/human/E...
2,human,Ebvallo,Lymphoproliferative Disorders,tabelecleucel,tabelecleucel,4577,False,authorised,NaN,True,...,Pierre Fabre Medicament,NaN,2022-10-13,2023-03-09,2.0,Ebvallo is indicated as monotherapy for treatm...,NaN,2022-10-12T16:13:00Z,2023-03-10T13:40:00Z,https://www.ema.europa.eu/en/medicines/human/E...
3,human,Ronapreve,COVID-19 virus infection,"casirivimab, imdevimab","casirivimab, imdevimab",5814,False,authorised,J06BD,True,...,Roche Registration GmbH,"Immune sera and immunoglobulins,",2021-11-11,2023-02-24,3.0,Ronapreve is indicated for:Treatment of COVID-...,NaN,2021-11-12T16:30:00Z,2023-03-10T12:29:00Z,https://www.ema.europa.eu/en/medicines/human/E...
4,human,Cosentyx,"Arthritis, Psoriatic; Psoriasis; Spondylitis...",secukinumab,secukinumab,3729,False,authorised,L04AC10,False,...,Novartis Europharm Limited,Immunosuppressants,2014-11-20,2023-01-26,30.0,Plaque psoriasisCosentyx is indicated for the ...,NaN,2018-06-07T11:59:00Z,2023-03-09T18:53:00Z,https://www.ema.europa.eu/en/medicines/human/E...

### **Data Cleaning and Preprocessing**

In [3]:
# Check number of rows and columns
drugs_df.shape

(1988, 28)

In [4]:
drugs_df.describe()

       product_number  revision_number
count     1988.000000      1892.000000
mean      2634.774145        13.527484
std       1915.734686        11.647056
min         24.000000         0.000000
25%        715.750000         4.750000
50%       2544.500000        11.000000
75%       4351.000000        19.000000
max       6039.000000        89.000000

Below shows number of missing values in each column. These missing values could be either removed or keep as they are. Imputation may not be the best option as it may misrepresenting data.

In [5]:
# Chart showing missing values of each column
missing_values = drugs_df.isnull().sum()
missing_percentage = ((drugs_df.isnull().sum() / len(drugs_df)) * 100).round(2)

missing_info = pd.DataFrame({
    'Missing Count': missing_values,
    'Missing Percentage (%)': missing_percentage
})

display(missing_info.sort_values(by='Missing Count', ascending=False))

,Missing Count,Missing Percentage (%)
date_of_refusal_of_marketing_authorisation,1913,96.23
species,1709,85.97
date_of_opinion,779,39.19
therapeutic_area,285,14.34
revision_number,96,4.83
marketing_authorisation_date,60,3.02
decision_date,45,2.26
pharmacotherapeutic_group,34,1.71
revision_date,29,1.46
atc_code,28,1.41
condition_indication,12,0.60
common_name,4,0.20
marketing_authorisation_holder_company_name,4,0.20
active_substance,1,0.05
authorisation_status,1,0.05
additional_monitoring,0,0.00
product_number,0,0.00
category,0,0.00
medicine_name,0,0.00
patient_safety,0,0.00
biosimilar,0,0.00
generic,0,0.00
accelerated_assessment,0,0.00
orphan_medicine,0,0.00
conditional_approval,0,0.00
exceptional_circumstances,0,0.00
first_published,0,0.00
url,0,0.00

In [6]:
# Information of values of the variable 'species'
unique_species_with_nan = drugs_df['species'].value_counts(dropna=False)
print("\nUnique values and their counts (including NaN) in 'species' column:")
print(unique_species_with_nan)

Unique values and their counts (including NaN) in 'species' column:
species
NaN                                                                    1709
Dogs                                                                     70
Cats                                                                     28
Pigs                                                                     25
Dogs; Cats                                                               18
Horses                                                                   18
Chicken                                                                  15
Cattle                                                                   10
Cattle; Pigs; Sheep                                                       7
Sheep; Cattle                                                             6
Cats; Dogs                                                                5
Sheep                                                                     5
Rabbits                                                                   4
Pigs (gilts and sows)                                                     4
Pigs (for fattening)                                                      3
Pigs; Cattle                                                              3
Horses; Pigs; Cattle                                                      3
Calves, newborn                                                           3
Cattle; Sheep                                                             3
Pigs (piglets)                                                            3
Pigs; Cattle; Sheep                                                       2
Chicken; Ducks                                                            2
Embryonated chicken eggs; Chicken                                         2
Cattle (cows and heifers)                                                 2
Chicken; Embryonated chicken eggs                                         2
Bees                                                                      2
Dogs; Cats; Cattle; Pigs                                                  1
Male pigs (from 8 weeks of age); Female pigs (from 14 weeks of age)       1
Calves, neonatal less than 12 hrs of age                                  1
Dogs; Horses; Cats; Cattle; Pigs                                          1
Horses; Dogs; Cattle; Cats; Pigs; Guinea pigs                             1
Embryonated eggs; Chicken                                                 1
Cats; Dogs; Ferrets                                                       1
Horses; Dogs; Cattle; Cats; Pigs                                          1
Chicken; Turkeys                                                          1
Chicken; Embryonated eggs                                                 1
Dogs (small)                                                              1
Pigs (sows for reproduction)                                              1
Pheasants; Chicken; Turkeys; Pigs                                         1
Horses; Dogs; Cats; Cattle; Pigs                                          1
Dogs; Cats; Guinea pigs                                                   1
Sows; Sows (nullipar)                                                     1
Red foxes (Vulpes vulpes); Raccoon dogs (Nyctereutes procyonoides)        1
Dogs; Cats; Ferrets                                                       1
Cattle (cows and heifers); Cattle                                         1
Atlantic salmon                                                           1
Dogs; Ferrets                                                             1
Goats; Cattle                                                             1
Ducks                                                                     1
Avian                                                                     1
Dogs; Cats; Cattle; Pigs; Horses                                          1
Pigs; Rabbits                                                             1
Raccoon dogs (Nyctereutes procyonoides); Red foxes (Vulpes vulpes)        1
Honey bees                                                                1
Turkeys; Dogs; Cattle; Chicken                                            1
Pigs; Chicken                                                             1
Pigs; Calves                                                              1
Dogs; Salmonidae (Salmonid fish)                                          1
Horses; Dogs; Cats                                                        1
Turkeys; Chicken                                                          1
Name: count, dtype: int64

In [7]:
# Get the count of all unique values, including NaN, for 'authorisation_status'
unique_auth_status_with_nan = drugs_df['authorisation_status'].value_counts(dropna=False)
print("Unique values and their counts (including NaN) in 'authorisation_status' column:")
print(unique_auth_status_with_nan)

# You can apply the same to other columns as needed, for example 'category'
unique_category_with_nan = drugs_df['category'].value_counts(dropna=False)
print("\nUnique values and their counts (including NaN) in 'category' column:")
print(unique_category_with_nan)

Unique values and their counts (including NaN) in 'authorisation_status' column:
authorisation_status
authorised    1573
withdrawn      357
refused         57
NaN              1
Name: count, dtype: int64

Unique values and their counts (including NaN) in 'category' column:
category
human         1706
veterinary     282
Name: count, dtype: int64